[package]
name = "agglayer-aggregator-notifier"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

agglayer-certificate-orchestrator = { path = "../agglayer-certificate-orchestrator" }
agglayer-config = { path = "../agglayer-config" }
pessimistic-proof = { path = "../pessimistic-proof" }

sp1-sdk.workspace = true

[features]
sp1-tests = ["sp1-mock", "sp1-local", "sp1-network"]
sp1-mock = []
sp1-local = []
sp1-network = []
